### ISSUE TITLE
allow returning promise

### ISSUE THREAD

**Issue by danielmhair** [fulls1z3/ngx-config#132]
**I'm submitting a...
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**Current behavior**
1. Using an Angular app (v. 5.2.6), import the following into app.module:
```
ConfigModule.forRoot({
  deps: [HttpClient],
  provide: ConfigLoader,
  useFactory: configFactory,
}),
```
where `configFactory` is:
```
export function configFactory(http: HttpClient): ConfigLoader {
  return new ConfigHttpLoader(http)
}
```
Then use `getSettings` in a service:
```
@Injectable()
export class MyService {
  constructor(private configService: ConfigService) {
    const url = configService.getSettings("api.url", "")
  }
}
```
**`url` would always be empty string**, when in my config.json file was this:
```
{
  "api": {
    "url": "www.example.com/api"
  }
}
```
This is mainly because the HttpLoader is most likely not finished with getting config.json by the time the constructor in my service calls `getSettings`.

**Expected/desired behavior**
Same code, except have two methods: `getSettingsSync` and `getSettings`, where `getSettings` returns a Promise or Observable when the service is finished with getting the settings.

Then in my code, I would go back to `MyService` and do this:
```
constructor(private configService: ConfigService) {
  const url = await configService.getSettings("api.url")
}
```

**What is the motivation / use case for changing the behavior?**
It is nice to have the getSettings method to **always** return your expected configuration. Since it didn't do this, it took me about 2-4 hours to realize why.

**Environment**
* **Angular version:** 5.2.6

* **Browser:**
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by fulls1z3** [comment]
@danielmhair first of all thanks for suggesting this feature, and I really appreciate each of them 😄 

I think I more or less understood your case.

Actually, any of those `ConfigLoader`s are appended to `APP_INITIALIZER` lifecycle hook of the app, so in any of your services you should be able to access the configuration through the scalar method `getSettings()`.

If the app is already initalized, then there're no problems.

However, there are some race conditions (*ex: server-side rendering, injecting HTTP interceptors, etc.*) where the app has not been initalized yet. For such cases I suggest you to pass an injector to the service and delay the invocation of `getSettings` method.

To make an example, and provide reference I'm hereby sharing a sample HTTP interceptor below:

```TypeScript
// angular
import { Injectable, Injector } from '@angular/core';
import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';

// libs
import { Observable } from 'rxjs';
import { mergeMap } from 'rxjs/operators';
import { get, getOr } from 'lodash/fp';
import { ConfigService } from '@ngx-config/core';
import { Auth0Service } from '@ngx-auth/auth0';

@Injectable()
export class JwtInterceptor implements HttpInterceptor {
  constructor(private readonly injector: Injector) {
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return Observable.create((observer: any) => {
      const item = this.injector.get(ConfigService);
      observer.next(item);
      observer.complete();
    })
      .pipe(
        mergeMap((res: ConfigService) => {
          const settings = res.getSettings('');
          const baseUrl = getOr('', 'backend.baseUrl', settings);

          if (get('auth', settings) && baseUrl && request.url.indexOf(baseUrl) >= 0) {
            const auth = this.injector.get(Auth0Service);

            if (auth && auth.accessToken)
              request = request.clone({
                setHeaders: {Authorization: `Bearer ${auth.accessToken}`}
              });
          }

          return next.handle(request);
        })
      );
  }
}
```

Don't forget to let me know about the results! 👍

**Comment by FritzHerbers** [comment]
@fulls1z3 I have the same or a similar problem.

Your HTTP interceptor will/might solve the problem when _ConfigService_ is not yet initialized. 
It does not solve the problem with a call to _GetSettings_ (within _mergeMap_) with a resolved _ConfigService_ as the HTTP request initiated by the _ConfigHttpLoader_ has not yet returned data.

I have a service, in the constructor I receive an initialized _ConfigService_, but the call to _GetSettings_ fails, as no config is yet available. (I think the OP has the same problem).

Is there a possibility to wait for the HTTP request to finish before calling _getSettings_ or have _getSettings_ to wait until the config is available ?

**Comment by FritzHerbers** [comment]
Instead of _ConfigHttpLoader_ i tried with _ConfigStaticLoader_.
The situation is the same, the Promise has not been resolved at the time the Service (used in an ngrx Effects) initializes.

**Comment by salem84** [comment]
I have the same problem... I cannot use angular-oauth2-oidc module initialization using JSON configurations.
Any news?

**Comment by djmcgrath101** [comment]
I managed to resolve this by using the `loadSettings()` method of the `loader` property in `ConfigService` which returns a Promise.  Don't know what possible side effects this might have but it worked for me.

**Comment by unlight** [comment]
@fulls1z3 
Is somebody working on this? Similar issues #147

**Comment by unlight** [comment]
As a stop gap solution `CustomConfigHttpLoader`
```js
import { ConfigHttpLoader } from '@ngx-config/http-loader';
import pDefer from 'p-defer';

export class CustomConfigHttpLoader extends ConfigHttpLoader {
    readonly onLoadSettings = pDefer();

    async loadSettings(): Promise<void> {
        const result = await super.loadSettings();
        this.onLoadSettings.resolve();
        return result;
    }
}
```
in other app initializer
```js
(configService.loader as CustomConfigHttpLoader).onLoadSettings.promise.then(() => {
console.log('loaded');
}));
```
