### ISSUE TITLE
when is it planned to get @ngx-config/fs-loader: 6.0.0 on npmjs.org?

### ISSUE THREAD

**Issue by mappedinn** [fulls1z3/ngx-config#144]
When is it planned to get the `@ngx-config/fs-loader`: 6.0.0 on [https://www.npmjs.com/package/@ngx-config/fs-loader](https://www.npmjs.com/package/@ngx-config/fs-loader/v/5.0.0) ?

thank

**Comment by alexburykin** [comment]
+1

**Comment by ganolmc** [comment]
+1

**Comment by TatianaBir** [comment]
+1

**Comment by 4doge** [comment]
We need this ASAP.
If you need some help just let me know.

**Comment by max-prosper** [comment]
+

**Comment by max-prosper** [comment]
+++

**Comment by tiger24l7** [comment]
+1

**Comment by Rizerin** [comment]
+1
