### ISSUE TITLE
ConfigModule should be importable in every module

### ISSUE THREAD

**Issue by UserGalileo** [fulls1z3/ngx-config#149]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

The module gives an error if you import ConfigModule twice.

**Expected/desired behavior**

Since ConfigModule exports a pipe (which must be declared in every module which uses it) it should be imported in other modules, too, without forRoot.
It should be fine removing the check in the constructor of the module. Then, whoever uses it must be sure to use forRoot only once with the main injector.

**Environment**
* **Angular version:** 7

**Comment by unlight** [comment]
ping @fulls1z3

**Comment by fulls1z3** [comment]
@UserGalileo @unlight sorry for the delay, had busy times. feel free to fire a PR and i'll approve.
