### ISSUE TITLE
add `suppressErrors` param to ConfigLoader

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-config#15]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```
As discussed on https://github.com/ngx-config/merge-loader/issues/3

**Comment by zjx20** [comment]
Instead of adding the new parameter, maybe it's better to let users be able to install their own error handler? As https://github.com/ngx-config/http-loader/issues/1 mentioned.
