### ISSUE TITLE
add pipe

### ISSUE THREAD

**Issue by froodley** [fulls1z3/ngx-config#16]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**

**Expected/desired behavior**

This module is great, but it would be very helpful if you introduced a pipe

**Minimal reproduction of the problem with instructions**

n/a

**What is the motivation / use case for changing the behavior?**

Accessing config strings from templates
**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **Browser:** [all  ]

 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =   6.9

**Comment by zjx20** [comment]
It does come with a pipe, please take a look at the readme. https://github.com/ngx-config/core#pipe
