### ISSUE TITLE
Function calls are not supported in decorators but 'ConfigModule' was called.

### ISSUE THREAD

**Issue by vadal** [fulls1z3/ngx-config#163]
**I'm submitting a ...**  (check one with "x")
```
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

`export function configLoaderFactory(http: HttpClient): ConfigLoader {`
`  const endpoint = `./assets/configuration/config.json`;`
`  return new ConfigHttpLoader(http, endpoint);`
`}`

`@NgModule({`
`  imports: [`
`    ConfigModule.forRoot({`
`      provide: ConfigLoader,`
`      useFactory: configLoaderFactory,`
`      deps: [HttpClient]`
`    })`
`  ],...`
This code causes the following error, when I try to update angular version to 9.
**Error: error TS100: Error during template compile of 'AppConfigModule'
     Function calls are not supported in decorators but 'ConfigModule' was called.**
Any idea?

**Expected/desired behavior**

I should not cause an error.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** 9.1.6

* **ngx-config/core version:** 9.0.0
* **Browser:**
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 12.16.1  
- Platform: Mac 

* Others:

**Comment by anvial** [comment]
The same error in prod build

**Comment by AncelHernandez** [comment]
This issue is resolved by updating the `tsconfig.package.json` file to disable compiling the lib with ivy.
```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

When you build a lib with ivy the cli gives you a warning.
```
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility
```
Would push up a PR but i don't have permission.

**Comment by AncelHernandez** [comment]
PR Created, first PR on an open source repo so bare with me 😅

**Comment by elendil-software** [comment]
Any news about this issue/PR ?

I have the same problem.

Regards

**Comment by s-albert** [comment]
I have the same problem when I run "ng xi18n" (while ng build is fine): ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'ConfigModule' was called. When I comment out ConfigModule.forRoot ng xi18n returns without an error.

**Comment by fulls1z3** [comment]
see https://github.com/fulls1z3/ngx-config/pull/169
