### ISSUE TITLE
manually trigger configuration resolution/load in AppComponent.ngOnInit.

### ISSUE THREAD

**Issue by skorunka** [fulls1z3/ngx-config#17]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Configuration is loaded before AppComponent.ngOnInit.

**Expected/desired behavior**
I would like to trigger config load manually, inside AppComponent.ngOnInit.

**Minimal reproduction of the problem with instructions**
```json
@NgModule({
	bootstrap: [AppComponent],
	declarations: [
		AppComponent
	],
	imports: [routing,
		ConfigModule.forRoot({ provide: ConfigLoader, useFactory: (configFactory), deps: [Http, AdalService] }),
	],
	providers: [
		{ provide: 'ORIGIN_URL', useValue: location.origin },
	]
})
export class AppModule { }

export function configFactory(http: Http, adalService: AdalService): ConfigLoader {
	const staticConfiguration = {
		apiUrls: {
			'app': environment.anticipateApiUrl + '/app'
		}
	};
	const configBuilder = new ConfigMergeLoader([new ConfigStaticLoader(staticConfiguration)]);
	return adalService.userInfo.isAuthenticated ? configBuilder.next((res: any) => new ConfigHttpLoader(http, res.apiUrls['app'] + '/configuration')) : configBuilder;
}
```

**What is the motivation / use case for changing the behavior?**
The request to get config from WebAPI using ConfigHttpLoader must be authenticated. Authentication is resolved in `AppComponent.ngOnInit` using `adalService.handleWindowCallback()`

**Please tell us about your environment:**
NPM 5.0.2, Windows 10, VS2017

* **Angular version:** 4.1.3

* **Browser:**  all 

* **Language:** all

* **Node (for AoT issues):** `node --version` = 8

**Comment by logan-jobzmall** [comment]
This is a great suggestion. We are running into an issue on NativeScript where they don't allow for promises on app init. +1
