### ISSUE TITLE
example of how to use with `ngrx` v4 and `effects`?

### ISSUE THREAD

**Issue by pjmagee** [fulls1z3/ngx-config#18]
**I'm submitting a ... (check one with "x")**

**[ ] bug report => check the README and search github for a similar issue or PR before submitting** 
**[X] support request => check the README and search github for a similar issue or PR before submitting** 
**[] feature request**

I'm currently using ngrx and have migrated to v4 which is inline with Angular4 versioning (they want to make this the standard way of developing angular4 apps with the ngrx platform). Previously I was able to get my configuration bootstrapped prior to the ngrx effects being loaded immediatley but now in the ngrx v4 the effects seem to be loaded instantly and I'm not sure how I can now bootstrap my configuration. Because my ngrx effects are being injected with the config service and now the values are undefined because they are instantiated because the config is bootstrapped. This is quite a major breaking change from the ngrx side, however nobody has responded and I'm kind of looking at this repo with your knowledge to see if maybe you might have some working examples with applications that will use the ngrx platform.

**Comment by fulls1z3** [comment]
@pjmagee I think I understood what you meant. It seems like `@ngrx` began to use `APP_INITIALIZER` to resolve the effects before the app gets bootstrapped - as `@ngx-config` does. However, there's no interface which allows to prioritize the execution of functions supplied by the `APP_INITIALIZER`.

I would recommend to change the order of imports (*at the app.module.ts, in NgModule section for instance*) and see those values are still undefined or not.

Also try to update this post after you make some tries, and meanwhile I'll see what can I do for this.

**Comment by fulls1z3** [comment]
@pjmagee I chosen one of my projects as a *victim* and upgraded the **ngrx** to `v4.0`. It took a few hours, but got it running somehow. I tried to get the state of an object which comes from ngx-config (*language*) and resulted OK.

Well, `resulted OK` is such a very generic expression - I'm aware of that.

Is it possible for you to post the repro steps (*github, plunkr, etc*) so that I can try to have a look. Well, it might be a commercial project, or could take much time to elaborate even a smaller version.

I'll try to integrate **ngrx** `v4.x` to [ng-seed/universal](https://github.com/ng-seed/universal) on the upcoming weeks (*might be even closer, but don't want to cite a very precise and optimistic time*) and maybe it could give you some clue.

**Comment by pjmagee** [comment]
I always ensure the `ConfigModule` is defined first in the imports list. Then I define near the bottom my `EffectsModule`. It seems like I'm looking for something now called `ngrxOnRunEffects` https://github.com/ngrx/platform/issues/174

Essentially my problem is, I have a `UserEffects` that has a `Security Service` which takes the ngx-config service. This Security service has end points required for the user to login (I use Identity Server 4) so I need external endpoints to manage authentication. So this configuration really does need to happen before ANY ngrx effects are triggered. Because my Security Service is injected into multiple Effects I have. 

I'm not sure how this ngrxOnRunEffects solve my problem, because my Security service is already injected into the Effect at that point. I can try to defer calling the config service GetSettings function and see how it plays out. 

No matter what I try, it just appears that ConfigService never has the keys/values set in time, even once the page has rendered. So yeah, not sure how I can do this.

```javascript
class Effects {  
   constructor(securityService: SecurityService) { } 
} 

class SecurityService { 
  constructor(configService: ConfigService) { }
 
  // configService getSettings() undefined v4.0
  // configService getSettings() defined perfectly pre v4.0 using RunAfterBootstrap
} 

@NgModule({ imports [  
          ConfigModule.forRoot({   // produces my ConfigService from Http to be injected into any Service 
            provide: ConfigLoader,
            useFactory: (createConfigLoader),
            deps: [Http, [ORIGIN_URL]]
        }),
        ...,
        EffectsModule.forRoot(EFFECTS) // new ngrx v4.0 (config settings always undefined)
        // Effects.RunAfterBootstrap(Effects) // pre ngrx v4.0 (config settings worked fine)
     ]})
class AppModule {

}

**Comment by fulls1z3** [comment]
@pjmagee you can have a look at [ng-seed/universal](https://github.com/ng-seed/universal), commit [6a50aac](https://github.com/ng-seed/universal/commit/6a50aaca668a2cb8caa8fe5427ab6dd62b14e388) which closes https://github.com/ng-seed/universal/pull/70.
