### ISSUE TITLE
using `ReflectiveInjector` with `ConfigService`

### ISSUE THREAD

**Issue by tkir** [fulls1z3/ngx-config#19]
Hi,
when I usesed ReflectiveInjector with ConfigService I got an error:
Uncaught Error: No provider for ConfigLoader! (ConfigService -> ConfigLoader)

`let injector = ReflectiveInjector.resolveAndCreate([ConfigService]);
    this.config = injector.get(ConfigService);`

**Comment by fulls1z3** [comment]
@tkir actually from this description I can't exactly figure out where do you use the `ReflectiveInjector`. However, as the error message says, you need to resolve `ConfigLoader` first (*which might not be that easy, you'll need to provide config params too for the loader*) and then resolve `ConfigService`: that's the dependency tree.
