### ISSUE TITLE
option to use an imported configuration file 

### ISSUE THREAD

**Issue by JonnyBGod** [fulls1z3/ngx-config#2]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**
Only works with http loaded config file

**Expected/desired behavior**
Provide the option to load an imported config file for compile time loading.

**What is the motivation / use case for changing the behavior?**
Better performance and security.

**Comment by fulls1z3** [comment]
Added `ConfigStaticLoader` with [5b4d88](https://github.com/nglibs/config/commit/35ffcef7c90fcdc062085f56575f211d8b1b84cc)
