### ISSUE TITLE
sample karma test of app that uses ngx-config

### ISSUE THREAD

**Issue by datasmithtech** [fulls1z3/ngx-config#22]
I'm submitting a 
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Support request => 
[ ] Feature request
[x] Documentation issue or request

I require a sample karma test of an app that uses ngx-config, so i may follow how to create a karma test spec of an angular app that uses ngx-config

**Comment by fulls1z3** [comment]
@datasmithtech actually yes, but last week I moved all projects into a single repository and `karma config` needs further improvisation.

You can use the `spec.ts` files, they're alright. And the `karma config`, better copy from `ng-seed/universal`:

- https://github.com/ng-seed/universal/blob/master/config/karma.conf.js
- https://github.com/ng-seed/universal/blob/master/config/spec-bundle.js

Finally, the `webpack.test.js`, copy it from `ngx-ps'
- https://github.com/fulls1z3/ngx-ps/blob/master/config/webpack.test.js

These config files should work without a problem. In case of trouble, let me know!

**Comment by datasmithtech** [comment]
i referred to your files, however, i created my project using ng cli, so i think majority of settings should be fine. i.e. hestitate to change anything, since not familiar with webpack

i now get following error
TypeError: this.loader.loadSettings is not a function
    at ConfigService.webpackJsonp.../../../../@ngx-config/core/src/config.service.js.ConfigService.init (http://localhost:9876/_karma_webpack_/webpack:/Users/dev/projects/wcoc-client-dev/~/@ngx-config/core/src/config.service.js:10:1)
    at Array.res (http://localhost:9876/_karma_webpack_/webpack:/Users/dev/projects/wcoc-client-dev/~/@ngx-config/core/index.js:13:28)

**Comment by fulls1z3** [comment]
@datasmithtech finally I managed to solve the issues with tests, and switched to the faster alternative: the *jest* platform.

You can have a look at the test configuration on this repo.
