### ISSUE TITLE
use HttpClient (4.3.0+) instead of Http

### ISSUE THREAD

**Issue by Shinzah** [fulls1z3/ngx-config#23]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[X ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
The project depends on @angular/http module which will be replaced by new @angular/common/http module.

**Expected/desired behavior**
Remove dependency to @angular/http and use @angular/common/http

**Environment**
* **Angular version:** 4.3.6

**Comment by fulls1z3** [comment]
@Shinzah thanks for pointing this out, I was also planning the same.

Currently I'm working on `ng-seed/universal` (*implementing ngrx, material2, etc*) but soon, we will be there.

**Comment by Shinzah** [comment]
Hi, any news about it ?

**Comment by artigat1** [comment]
Any new about this? The latest release has Http marked as deprecated, so in a release in the near future, it will  no longer exist, which will break my application as I rely on this plugin to load my config.

**Comment by fulls1z3** [comment]
done
