### ISSUE TITLE
merge-loader doesn't merge

### ISSUE THREAD

**Issue by punund** [fulls1z3/ngx-config#54]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
Merge loader doesn't merge configs, the latter replaces the former.

**Expected/desired behavior**
Merge loader should merge.

**Minimal reproduction of the problem with instructions**

````
export function configFactorySeries(http: Http): ConfigLoader {
    const localConfigLoader = new ConfigStaticLoader({
        MyData: ['aa', 'bb']
        })

    const httpConfigLoader = new ConfigHttpLoader(http, './assets/config.json')

  return new ConfigMergeLoader([localConfigLoader])
    .next((res: any) => httpConfigLoader)
}
````

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** 4.3.3

* **Browser:**
- [x ] Chrome (desktop) version XX

* **For Tooling issues:**
- Node version: 6.11.3
- Platform:  Linux

* Others:
This happens when merging HttpConfig with LocalConfig.

**Comment by zjx20** [comment]
In short: we treat arrays as “values” but not something special, we merge objects but not arrays.

Assume that we are merging `a = [1, 2]` and `b = [3, 4]`. You expect the result to be `[1, 2, 3, 4]`, right? But what if someone want it to be `[3, 4]`, or even `[3, 4, 1, 2]`? All of them are meaningful use cases.

For now we don't merge arrays, so users have the chance to choose what the merging result should be. For your case, you can make `a = [1, 2]` and `b = [1, 2, 3, 4]`, and then `ngx-config` gives you `[1, 2, 3, 4]`.
