### ISSUE TITLE
token replacement on paths (ConfigMergedHttpLoader)

### ISSUE THREAD

**Issue by fulls1z3** [fulls1z3/ngx-config#8]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[X] feature request
```

> As mentioned in #4, @zjx20:
> Now, we have such an use case, and I would like to listen to your ideas:
> 
> - Let's say we have two config files: `config.local.json`, and `http://some-api-provider.com/api/get-settings`.
> - We pass these locations to the `paths` property of `ConfigMergedHttpLoader`.
> - We want `ConfigService` processes those two config files sequentally, and replace the API URL `some-api-provider` with a value from `config.local.json`.
> 
> In other words:
> 
> #### config.local.json
> ```json
> {
>   "api-endpoint": "http://some-api-provider/api"
> }
> ```
> 
> #### app.module
> ```TypeScript
> const configFactory(http: Http): ConfigLoader {
>   return new ConfigMergedHttpLoader(http, ['./config.local.json', '{{api-endpoint}}/get-settings'])
> }
> ```
>

**Comment by zjx20** [comment]
Thank you for asking me this. I thought for a while, and I think the approach you described adds complexity to `ConfigMergedHttpLoader`, especially the replacement magic. It will make `ConfigMergedHttpLoader` hard to implement and hard to understand.

Here is my solution for your reference.

First of all, we enhance `ConfigLoader` and `ConfigService` for a multi-stage bootstrap, say:

```ts
export abstract class ConfigLoader {
  abstract loadSettings(): any;
  abstract nextConfigLoader(loadedSettings?: any): ConfigLoader;
}

export class ConfigService {
  // omitted...

  init(): any {
    // Recursively call loader.loadSettings() and loader.nextConfigLoader(this.settings)
    // until the next config loader is null.
    // return a promise object for that procedure.
  }

  // omitted...
}
```

And then we can provide a general implementation of `nextConfigLoader`, here we go:

```ts
export class ChainableConfigLoader implements ConfigLoader {
  private nextConfigLoaderFactory: Function;  // a function returns a ConfigLoader

  abstract loadSettings(): any; // keep it unimplemented

  nextConfigLoader(loadedSettings?: any): ConfigLoader {
    if (!this.nextConfigLoaderFactory) {return null;}
    return this.nextConfigLoaderFactory(loadedSettings);
  }

  chainConfigLoaderFactory(factory: Function) {
    this.nextConfigLoaderFactory = factory;
  }
}

// make all provided loaders chainable
export class ConfigHttpLoader extends ChainableConfigLoader {
  // omitted...
}

// omitted other loaders...
```

Finally, your described use case can be expressed in this way:

```ts
const configFactory(http: Http): ConfigLoader {
  return new ConfigMergedHttpLoader(http, ['./config.json', './config.local.json'])
    .chainConfigLoaderFactory((loadedSettings: any) => {
      return new ConfigHttpLoader(http, loadedSettings["api-endpoint"] + "/get-settings");
    });
}
```

**Comment by fulls1z3** [comment]
Awesome idea @zjx20, thank you very much 👍 

In that case, seems like we will have 2 **magic** loaders: series (chainable) and parallel (merged) ones.

**Comment by zjx20** [comment]
Glad you like the proposal. I think the most difficult part is the `ConfigService`, I just can't write couple of lines to implement it (probably limited by my js skill).

**Comment by fulls1z3** [comment]
It looks like you've got good skills. Furthermore, it's the **idea** which makes the software.

I'll draft something within this week (hope) and let's have a look together.

**Comment by fulls1z3** [comment]
Moved to https://github.com/ngx-config/parallel-loader/issues/1
